using System;
using System.Data;

namespace FF.BusinessObjects
{
    //===========================================================================================================
    // This code is generated by Code gen V.1
    // Computer :- ITPD11  | User :- suneth On 27-Nov-2014 10:20:54
    //===========================================================================================================

    public class Service_Close_Type
    {
        public String SCT_TP { get; set; }
        public String SCT_DESC { get; set; }
        public Int32 SCT_ACT { get; set; }
        public String SCT_PREFIX { get; set; }
        public Int32 SCT_ISFOC { get; set; }
        public Int32 SCT_REPL_ALLOW { get; set; }
        public static Service_Close_Type Converter(DataRow row)
        {
            return new Service_Close_Type
            {
                SCT_TP = row["SCT_TP"] == DBNull.Value ? string.Empty : row["SCT_TP"].ToString(),
                SCT_DESC = row["SCT_DESC"] == DBNull.Value ? string.Empty : row["SCT_DESC"].ToString(),
                SCT_ACT = row["SCT_ACT"] == DBNull.Value ? 0 : Convert.ToInt32(row["SCT_ACT"].ToString()),
                SCT_PREFIX = row["SCT_PREFIX"] == DBNull.Value ? string.Empty : row["SCT_PREFIX"].ToString(),
                SCT_ISFOC = row["SCT_ISFOC"] == DBNull.Value ? 0 : Convert.ToInt32(row["SCT_ISFOC"].ToString()),
                SCT_REPL_ALLOW = row["SCT_REPL_ALLOW"] == DBNull.Value ? 0 : Convert.ToInt32(row["SCT_REPL_ALLOW"].ToString())
            };
        }
    }
}