using System;
using System.Data;

namespace FF.BusinessObjects
{
    //===========================================================================================================
    // This code is generated by Code gen V.1 
    // Computer :- ITPD11  | User :- suneth On 01-Apr-2015 12:18:43
    //===========================================================================================================

    public class SR_TRANS_CHA
    {
        public Int32 STC_SEQ { get; set; }
        public String STC_COM { get; set; }
        public String STC_SER_BY { get; set; }
        public String STC_CATE { get; set; }
        public String STC_CD { get; set; }
        public DateTime STC_FRM_DT { get; set; }
        public DateTime STC_TO_DT { get; set; }
        public String STC_FRM { get; set; }
        public String STC_TO { get; set; }
        public String STC_CLS { get; set; }
        public String STC_VEH_TP { get; set; }
        public Int32 STC_FRM_KM { get; set; }
        public Int32 STC_TO_KM { get; set; }
        public Decimal STC_RT { get; set; }
        public Decimal STC_AD_RT { get; set; }
        public String STC_RT_TP { get; set; }
        public String STC_CRE_BY { get; set; }
        public DateTime STC_CRE_DT { get; set; }
        public String STC_MOD_BY { get; set; }
        public DateTime STC_MOD_DT { get; set; }

        public String STC_CURR { get; set; }
        public String STC_DESC { get; set; }
        public Int32 STC_ACT { get; set; }
        public decimal STC_TAX_RT { get; set; }
        public string STC_PC { get; set; }
        public static SR_TRANS_CHA Converter(DataRow row)
        {
            return new SR_TRANS_CHA
            {
                STC_SEQ = row["STC_SEQ"] == DBNull.Value ? 0 : Convert.ToInt32(row["STC_SEQ"].ToString()),
                STC_COM = row["STC_COM"] == DBNull.Value ? string.Empty : row["STC_COM"].ToString(),
                STC_SER_BY = row["STC_SER_BY"] == DBNull.Value ? string.Empty : row["STC_SER_BY"].ToString(),
                STC_CATE = row["STC_CATE"] == DBNull.Value ? string.Empty : row["STC_CATE"].ToString(),
                STC_CD = row["STC_CD"] == DBNull.Value ? string.Empty : row["STC_CD"].ToString(),
                STC_FRM_DT = row["STC_FRM_DT"] == DBNull.Value ? DateTime.MinValue : Convert.ToDateTime(row["STC_FRM_DT"].ToString()),
                STC_TO_DT = row["STC_TO_DT"] == DBNull.Value ? DateTime.MinValue : Convert.ToDateTime(row["STC_TO_DT"].ToString()),
                STC_FRM = row["STC_FRM"] == DBNull.Value ? string.Empty : row["STC_FRM"].ToString(),
                STC_TO = row["STC_TO"] == DBNull.Value ? string.Empty : row["STC_TO"].ToString(),
                STC_CLS = row["STC_CLS"] == DBNull.Value ? string.Empty : row["STC_CLS"].ToString(),
                STC_VEH_TP = row["STC_VEH_TP"] == DBNull.Value ? string.Empty : row["STC_VEH_TP"].ToString(),
                STC_FRM_KM = row["STC_FRM_KM"] == DBNull.Value ? 0 : Convert.ToInt32(row["STC_FRM_KM"].ToString()),
                STC_TO_KM = row["STC_TO_KM"] == DBNull.Value ? 0 : Convert.ToInt32(row["STC_TO_KM"].ToString()),
                STC_RT = row["STC_RT"] == DBNull.Value ? 0 : Convert.ToDecimal(row["STC_RT"].ToString()),
                STC_AD_RT = row["STC_AD_RT"] == DBNull.Value ? 0 : Convert.ToDecimal(row["STC_AD_RT"].ToString()),
                STC_RT_TP = row["STC_RT_TP"] == DBNull.Value ? string.Empty : row["STC_RT_TP"].ToString(),
                STC_CRE_BY = row["STC_CRE_BY"] == DBNull.Value ? string.Empty : row["STC_CRE_BY"].ToString(),
                STC_CRE_DT = row["STC_CRE_DT"] == DBNull.Value ? DateTime.MinValue : Convert.ToDateTime(row["STC_CRE_DT"].ToString()),
                STC_MOD_BY = row["STC_MOD_BY"] == DBNull.Value ? string.Empty : row["STC_MOD_BY"].ToString(),
                STC_MOD_DT = row["STC_MOD_DT"] == DBNull.Value ? DateTime.MinValue : Convert.ToDateTime(row["STC_MOD_DT"].ToString()),
                STC_CURR = row["STC_CURR"] == DBNull.Value ? string.Empty : row["STC_CURR"].ToString(),
                STC_DESC = row["STC_DESC"] == DBNull.Value ? string.Empty : row["STC_DESC"].ToString(),
                STC_ACT = row["STC_ACT"] == DBNull.Value ? 0 : Convert.ToInt32(row["STC_ACT"].ToString()),
                STC_TAX_RT = row["STC_TAX_RT"] == DBNull.Value ? 0 : Convert.ToDecimal(row["STC_TAX_RT"].ToString()),
                STC_PC = row["STC_PC"] == DBNull.Value ? string.Empty : row["STC_PC"].ToString()
            };
        }

        public static SR_TRANS_CHA Converter2(DataRow row)
        {
            return new SR_TRANS_CHA
            {

                STC_SER_BY = row["STC_SER_BY"] == DBNull.Value ? string.Empty : row["STC_SER_BY"].ToString(),
                STC_CLS = row["STC_CLS"] == DBNull.Value ? string.Empty : row["STC_CLS"].ToString(),
                STC_FRM_DT = row["STC_FRM_DT"] == DBNull.Value ? DateTime.MinValue : Convert.ToDateTime(row["STC_FRM_DT"].ToString()),
                STC_TO_DT = row["STC_TO_DT"] == DBNull.Value ? DateTime.MinValue : Convert.ToDateTime(row["STC_TO_DT"].ToString()),
                STC_FRM = row["STC_FRM"] == DBNull.Value ? string.Empty : row["STC_FRM"].ToString(),
                STC_TO = row["STC_TO"] == DBNull.Value ? string.Empty : row["STC_TO"].ToString(),
                STC_CURR = row["STC_CURR"] == DBNull.Value ? string.Empty : row["STC_CURR"].ToString(),
                STC_RT = row["STC_RT"] == DBNull.Value ? 0 : Convert.ToDecimal(row["STC_RT"].ToString()),
               
            };
        }
    }
}

